const counties = [
  {
    name: "Bedfordshire",
    country: "England",
    postalCode: "BF",
    coordinates: { lat: 52.1357, lng: -0.4667 },
  },
  {
    name: "Berkshire",
    country: "England",
    postalCode: "BK",
    coordinates: { lat: 51.4416, lng: -1.0 },
  },
  {
    name: "Bristol",
    country: "England",
    postalCode: "BS",
    coordinates: { lat: 51.4545, lng: -2.5879 },
  },
  {
    name: "Buckinghamshire",
    country: "England",
    postalCode: "BU",
    coordinates: { lat: 51.8135, lng: -0.8085 },
  },
  {
    name: "Cambridgeshire",
    country: "England",
    postalCode: "CB",
    coordinates: { lat: 52.2053, lng: 0.1218 },
  },
  {
    name: "Cheshire",
    country: "England",
    postalCode: "CH",
    coordinates: { lat: 53.2326, lng: -2.6103 },
  },
  {
    name: "London",
    country: "England",
    postalCode: "LDN",
    coordinates: { lat: 51.5128, lng: -0.0918 },
  },
  {
    name: "Cornwall",
    country: "England",
    postalCode: "CN",
    coordinates: { lat: 50.266, lng: -5.0527 },
  },
  {
    name: "Cumbria",
    country: "England",
    postalCode: "CU",
    coordinates: { lat: 54.5772, lng: -2.7975 },
  },
  {
    name: "Derbyshire",
    country: "England",
    postalCode: "DB",
    coordinates: { lat: 53.1224, lng: -1.5564 },
  },
  {
    name: "Devon",
    country: "England",
    postalCode: "DV",
    coordinates: { lat: 50.7156, lng: -3.5309 },
  },
  {
    name: "Dorset",
    country: "England",
    postalCode: "DT",
    coordinates: { lat: 50.7512, lng: -2.4487 },
  },
  {
    name: "Durham",
    country: "England",
    postalCode: "DH",
    coordinates: { lat: 54.7753, lng: -1.5849 },
  },
  {
    name: "East Yorkshire",
    country: "England",
    postalCode: "ERY",
    coordinates: { lat: 53.8008, lng: -0.3356 },
  },
  {
    name: "East Sussex",
    country: "England",
    postalCode: "ES",
    coordinates: { lat: 50.9369, lng: 0.268 },
  },
  {
    name: "Essex",
    country: "England",
    postalCode: "EX",
    coordinates: { lat: 51.745, lng: 0.4726 },
  },
  {
    name: "Gloucestershire",
    country: "England",
    postalCode: "GL",
    coordinates: { lat: 51.8642, lng: -2.2382 },
  },
  {
    name: "Greater London",
    country: "England",
    postalCode: "GLD",
    coordinates: { lat: 51.5074, lng: -0.1278 },
  },
  {
    name: "Manchester",
    country: "England",
    postalCode: "GM",
    coordinates: { lat: 53.4793, lng: -2.2479 },
  },
  {
    name: "Hampshire",
    country: "England",
    postalCode: "HM",
    coordinates: { lat: 51.0577, lng: -1.308 },
  },
  {
    name: "Herefordshire",
    country: "England",
    postalCode: "HF",
    coordinates: { lat: 52.0765, lng: -2.6544 },
  },
  {
    name: "Hertfordshire",
    country: "England",
    postalCode: "HT",
    coordinates: { lat: 51.8098, lng: -0.2377 },
  },
  {
    name: "Isle of Wight",
    country: "England",
    postalCode: "IW",
    coordinates: { lat: 50.6938, lng: -1.3047 },
  },
  {
    name: "Kent",
    country: "England",
    postalCode: "KE",
    coordinates: { lat: 51.2787, lng: 0.5215 },
  },
  {
    name: "Lancashire",
    country: "England",
    postalCode: "LA",
    coordinates: { lat: 53.7632, lng: -2.7044 },
  },
  {
    name: "Leicestershire",
    country: "England",
    postalCode: "LE",
    coordinates: { lat: 52.6369, lng: -1.1398 },
  },
  {
    name: "Lincolnshire",
    country: "England",
    postalCode: "LN",
    coordinates: { lat: 53.2307, lng: -0.5406 },
  },
  {
    name: "Merseyside",
    country: "England",
    postalCode: "ME",
    coordinates: { lat: 53.4084, lng: -2.9916 },
  },
  {
    name: "Norfolk",
    country: "England",
    postalCode: "NF",
    coordinates: { lat: 52.6309, lng: 1.2974 },
  },
  {
    name: "North Yorkshire",
    country: "England",
    postalCode: "NY",
    coordinates: { lat: 54.1324, lng: -1.5814 },
  },
  {
    name: "Northamptonshire",
    country: "England",
    postalCode: "NH",
    coordinates: { lat: 52.237, lng: -0.8977 },
  },
  {
    name: "Northumberland",
    country: "England",
    postalCode: "NB",
    coordinates: { lat: 55.097, lng: -1.5129 },
  },
  {
    name: "Nottinghamshire",
    country: "England",
    postalCode: "NG",
    coordinates: { lat: 53.14, lng: -1.1688 },
  },
  {
    name: "Oxfordshire",
    country: "England",
    postalCode: "OX",
    coordinates: { lat: 51.7519, lng: -1.2578 },
  },
  {
    name: "Rutland",
    country: "England",
    postalCode: "RU",
    coordinates: { lat: 52.668, lng: -0.7277 },
  },
  {
    name: "Shropshire",
    country: "England",
    postalCode: "SH",
    coordinates: { lat: 52.7073, lng: -2.7553 },
  },
  {
    name: "Somerset",
    country: "England",
    postalCode: "SO",
    coordinates: { lat: 51.0847, lng: -3.0331 },
  },
  {
    name: "South Yorkshire",
    country: "England",
    postalCode: "SY",
    coordinates: { lat: 53.501, lng: -1.1325 },
  },
  {
    name: "Staffordshire",
    country: "England",
    postalCode: "ST",
    coordinates: { lat: 52.8057, lng: -2.0871 },
  },
  {
    name: "Suffolk",
    country: "England",
    postalCode: "SF",
    coordinates: { lat: 52.134, lng: 1.0163 },
  },
  {
    name: "Surrey",
    country: "England",
    postalCode: "SR",
    coordinates: { lat: 51.3176, lng: -0.5599 },
  },
  {
    name: "Tyne and Wear",
    country: "England",
    postalCode: "TW",
    coordinates: { lat: 54.9784, lng: -1.6174 },
  },
  {
    name: "Warwickshire",
    country: "England",
    postalCode: "WK",
    coordinates: { lat: 52.2819, lng: -1.5845 },
  },
  {
    name: "West Midlands",
    country: "England",
    postalCode: "WM",
    coordinates: { lat: 52.4862, lng: -1.8904 },
  },
  {
    name: "West Sussex",
    country: "England",
    postalCode: "WS",
    coordinates: { lat: 50.912, lng: -0.3949 },
  },
  {
    name: "West Yorkshire",
    country: "England",

    postalCode: "WY",
    coordinates: { lat: 53.8008, lng: -1.5491 },
  },
  {
    name: "Wiltshire",
    country: "England",
    postalCode: "WI",
    coordinates: { lat: 51.3493, lng: -1.9927 },
  },
  {
    name: "Worcestershire",
    country: "England",
    postalCode: "WR",
    coordinates: { lat: 52.1936, lng: -2.2216 },
  },
];
