export const cities = [
  "London",
  "Birmingham",
  "Manchester",
  "Liverpool",
  "Leeds",
  "Sheffield",
  "Bristol",
  "Newcastle upon Tyne",
  "Sunderland",
  "Wolverhampton",
  "Nottingham",
  "Leicester",
  "Coventry",
  "Kingston upon Hull",
  "Stoke-on-Trent",
  "Derby",
  "Southampton",
  "Portsmouth",
  "Brighton and Hove",
  "Plymouth",
  "Norwich",
  "Oxford",
  "Cambridge",
  "Exeter",
  "York",
  "Bath",
  "Lancaster",
  "Chester",
  "Carlisle",
  "Worcester",
  "Gloucester",
  "Winchester",
  "Durham",
  "Lincoln",
  "Hereford",
  "Salisbury",
  "Ely",
  "Wells",
  "Ripon",
  "Lichfield",
  "Truro",
  "Wakefield",
  "Preston",
  "Salford",
  "Westminster",
  "Chelmsford",
  "St Albans",
  "Peterborough",
  "Southend-on-Sea",
  "Luton",
  "Milton Keynes",
  "Reading",
  "Slough",
  "Ipswich",
  "Bournemouth",
  "Swindon",
  "Middlesbrough",
  "Huddersfield",
  "Warrington",
  "Birkenhead",
  "Gateshead",
  "Blackpool",
  "Bolton",
  "Stockport",
  "Telford",
  "Hastings",
  "Eastbourne",
  "Worthing",
  "Colchester",
  "Basingstoke",
  "Crawley",
  "Sutton Coldfield",
  "Dudley",
  "Rochdale",
  "Solihull",
  "Watford",
  "Oldham",
  "Woking",
  "Hemel Hempstead",
  "Halifax",
  "St Helens",
  "Basildon",
  "Chatham",
  "Cheltenham",
  "Doncaster",
  "Poole",
  "Scunthorpe",
  "Rotherham",
  "Barnsley",
  "Wokingham",
  "Crewe",
  "Grimsby",
  "High Wycombe",
  "Aylesbury",
  "Bury",
  "Burnley",
  "Brentwood",
  "Bromley",
  "Bexley",
  "Enfield",
  "Hackney",
  "Haringey",
  "Harrow",
  "Islington",
  "Kensington and Chelsea",
  "Lambeth",
  "Lewisham",
  "Newham",
  "Redbridge",
  "Richmond upon Thames",
  "Southwark",
  "Sutton",
  "Tower Hamlets",
  "Waltham Forest",
  "Wandsworth",
  "Hillingdon",
  "Ealing",
  "Hammersmith and Fulham",
  "Hounslow",
  "Kingston upon Thames",
  "Merton",
  "Camden",
  "Barnet",
  "Waltham Abbey",
  "Hertford",
  "Stevenage",
  "Welwyn Garden City",
  "Hatfield",
  "Harpenden",
  "Bishop's Stortford",
  "Royston",
  "Ware",
  "Chorleywood",
  "Rickmansworth",
  "Abingdon",
  "Didcot",
  "Wantage",
  "Witney",
  "Kidlington",
  "Henley-on-Thames",
  "Wallingford",
  "Banbury",
  "Bicester",
  "Woodstock",
  "Alcester",
  "Atherstone",
  "Bedworth",
  "Kenilworth",
  "Nuneaton",
  "Rugby",
  "Stratford-upon-Avon",
  "Warwick",
  "Leamington Spa",
  "Southam",
  "Shipston-on-Stour",
  "Wellesbourne",
  "Redditch",
  "Studley",
  "Bromsgrove",
  "Bewdley",
  "Stourport-on-Severn",
  "Kidderminster",
  "Tenbury Wells",
  "Pershore",
  "Droitwich Spa",
  "Evesham",
  "Malvern",
  "Upton-upon-Severn",
  "Colwall",
  "Ledbury",
  "Leominster",
  "Ross-on-Wye",
  "Kington",
  "Bromyard",
  "Shrewsbury",
  "Oswestry",
  "Ludlow",
  "Church Stretton",
  "Bridgnorth",
  "Much Wenlock",
  "Wem",
  "Market Drayton",
  "Whitchurch",
  "Ellesmere",
  "Bishop's Castle",
  "Clun",
  "Cleobury Mortimer",
  "Albrighton",
  "Ironbridge",
  "Newport",
  "Smethwick",
  "Rowley Regis",
  "Tipton",
  "West Bromwich",
  "Shirley",
  "Olton",
  "Kingshurst",
  "Fordbridge",
  "Marston Green",
  "Hampton-in-Arden",
  "Knowle",
  "Hockley Heath",
  "Chelmsley Wood",
  "Castle Bromwich",
  "Barnt Green",
  "Beoley",
  "Romsley",
  "Rubery",
  "Catshill",
  "Astwood Bank",
  "Feckenham",
  "Wythall",
  "Hollywood",
  "Earlswood",
  "Tanworth-in-Arden",
  "Welford-on-Avon",
  "Brailes",
  "Bishop's Itchington",
  "Napton-on-the-Hill",
  "Fenny Compton",
  "Harbury",
  "Radford Semele",
  "Long Itchington",
  "Bishops Tachbrook",
  "Cubbington",
  "Leek Wootton",
  "Hatton",
  "Lapworth",
  "Balsall Common",
  "Meriden",
  "Walsall",
  "Sandwell",
  "Wednesbury",
];
